name: Sync Ardupilot Master

on:
  schedule:
  - cron: "0 0 * * *" # every hr. set to whatever interval you like

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 10  # greater than the number of commits you made
    - uses: ArduPilot/ardupilot@master
